version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    ports:
    - "8080:8080"
    - "9229:9229"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    command: "npm start"
